version: "3"
services:
  postgres_db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=mydbuser
      - POSTGRES_PASSWORD=mydbpass

  drf_app:
    build: ./backend/
    image: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

volumes:
  db:
